version: '2'
services:
    rutorrent-develop:
      image: romancin/rutorrent:develop3.9
      container_name: rutorrent-develop
      networks:
        - default
      tty: true
      environment:
        - PUID=0
        - PGID=0
        - TZ=Europe/Madrid
      ports:
        - "7443:443"
        - "42316:52316"
networks:
  default:
    external:
      name: main_network
