version: '2'
services:
    rutorrent:
      image: romancin/rutorrent:0.9.8
      container_name: rutorrent
      networks:
        - default
      tty: true
      volumes:
        - /share/Container/rutorrent:/config
        - /share/Container/rutorrent/downloads:/downloads
      environment:
        - PUID=0
        - PGID=0
        - TZ=Europe/Madrid
        - CREATE_SUBDIR_BY_TRACKERS=NO
        - SSL_ENABLED=NO
        - RT_TOKEN=
        - RT_MASTERS=
      ports:
        - "8080:80"
       #- "7443:443"
        - "32316:52316"
