name: ci

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          VER=$(cat VERSION)
          echo "VERSION=$VER" >> $GITHUB_ENV
          echo "USER=romancin" >> $GITHUB_ENV
          echo "REPO=rutorrent" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Docker Image (master branch)
        uses: docker/build-push-action@v2      
        with:
          context: .
          file: ${{ env.BASE_DIR }}/Dockerfile
          load: true
          push: true
          tags: |
            ${{ env.USER }}/${{ env.REPO }}:0.9.8-${{ env.VERSION }}
            ${{ env.USER }}/${{ env.REPO }}:latest
        if: github.ref == 'refs/heads/develop'
      - name: Build Docker Image (develop branch)
        uses: docker/build-push-action@v2      
        with:
          context: .
          file: ${{ env.BASE_DIR }}/Dockerfile
          load: true
          push: true
          tags: |
            ${{ env.USER }}/${{ env.REPO }}:develop-${{ env.VERSION }}
            ${{ env.USER }}/${{ env.REPO }}:develop
        if: github.ref == 'refs/heads/develop'